config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get '/auth/:provider/callback', to: 'sessions#create'

  get '/login',       to: 'sessions#new'
  post '/login',      to: 'sessions#create'
  delete '/logout',   to: 'sessions#destroy'

  resource :user, only: [:show, :edit, :update]
  resources :users, only: [:new, :index, :create]
  resources :bike_events, only: [:index, :new, :create, :destroy]

  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
end

app/models/bike_event.rb
class BikeEvent < ActiveRecord::Base
  validates :event_kind, :occurred_at, :details, :user_id, :latitude, :longitude, presence: true
  validate :valid_date
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  def valid_date
    if occurred_at && occurred_at.future?
      errors.add(:occurred_at, "Event can not be in the future")
    end
  end

  def date
    occurred_at.strftime('%m-%d-%y')
  end

  def time
    occurred_at.strftime('%I:%M %P')
  end

  def self.filter_by(type)
    if type.nil?
      all
    else
      where(event_kind: type)
    end
  end

  def pin_color
    case event_kind
      when 'Accident'
      "accident"  #key for icon in js land
      when 'Road Hazard'
      "hazard"  
      when 'Freak, wildlife incident'
      "animal" 
    else
      "other"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, presence: true
  validates :email, uniqueness: true

  has_many :bike_events
  
  has_secure_password

  def self.find_or_create_from_auth(auth)
    User.find_or_create_by(provider: auth.provider, uid: auth.uid).tap do |user|
      user.provider   = auth.provider
      user.uid        = auth.uid
      user.username   = auth.info.name
      user.email      = auth.info.email
      user.image_url  = auth.info.image
      user.token      = auth.credentials.token
      user.password   = "password"
       
      user.save!
      user
    end
  end

  def self.find_by_email(auth)
    User.find_by(email: auth.info.email).tap do |user|
      user.provider   = auth.provider
      user.uid        = auth.uid
      user.username   = auth.info.name
      user.email      = auth.info.email
      user.image_url  = auth.info.image
      user.token      = auth.credentials.token
      user.password   = "password"
       
      user.save!
      user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    #sessions user = current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize_user
    if !current_user
      redirect_to login_path, notice: "You must be logged in."
    end
  end
end

app/controllers/bike_events_controller.rb
class BikeEventsController < ApplicationController
  respond_to :json, :html
  before_action :authorize_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @bike_event ||= BikeEvent.new 

    respond_to do |format| 
      format.html
      format.json do 
        bike_events = BikeEvent.filter_by(params[:event_kind]).map do |bike_event|
          details = render_to_string(
            partial: 'show.html', 
            locals: { bike_event: bike_event }, 
            layout: false
          )
          { 
            latitude:   bike_event.latitude,
            longitude:  bike_event.longitude,
            id:         bike_event.id,
            event_kind: bike_event.event_kind,
            icon:       bike_event.pin_color,
            avatar:     bike_event.avatar,
            details:    details
          }
        end
        render json: bike_events 
      end 
    end
  end

  def new
    @bike_event = BikeEvent.new 
  end

  def create
    @bike_event = current_user.bike_events.new(bike_event_params)

      if @bike_event.save
        render partial: 'show', locals: { bike_event: @bike_event }, status: 201
      else
        render partial: 'partials/bike_events_errors', status: 422
      end
  end

  def edit
  end

  def destroy
    bike_event = BikeEvent.find(params[:id])
    bike_event.destroy
    head :no_content  
    # sends a 204
  end

  private
  def bike_event_params
    params.require(:bike_event).permit(:event_kind, :occurred_at, :details,
                                        :user_id, :latitude, :longitude, :avatar
                                      )
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: :not_found
  end

  def internal_server_error
    render status: :internal_server_error
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @body_class = "home"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize_user, only: [:destroy]

  def new
    @body_class = "login"
  end

  def create
    if params[:provider]
      login_with_google
    else
      login_by_email
    end
  end

  def destroy
    session.clear
    flash[:danger] = "Successfully logged out!"
    redirect_to root_path
  end

  private
  def login_by_email
    user = User.find_by(email: params[:session][:email])
    
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in!"
      redirect_to bike_events_path
    else
      flash[:danger] = "Invalid login. Please try again."
      redirect_to :back
    end
  end

  def login_with_google
    if email_associated_with_user_exists?
      user = User.find_by_email(auth)
    else
      user = User.find_or_create_from_auth(auth)
    end
    create_session(user)
    redirect_to root_path
  end

  def email_associated_with_user_exists?
    !User.find_by(email: auth.info.email).nil?
  end
  
  def auth
    request.env['omniauth.auth']
  end

  def create_session(user)
    if user
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in!"
    else
      flash[:danger] = "Invalid login. Please try again."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id 
      flash[:success] = "Account Created!"
      redirect_to root_path
    else
      render :new 
    end
  end

  private
  def user_params
    params.require(:user).permit( :username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bike_events_helper.rb
module BikeEventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bike_events/_form.html.erb
<div>
  <%= form_for(@bike_event, url: bike_events_path, :html => {:'data-type' => 'text'}, remote: true, method: :post, role:"form") do |f| %>

  <div class="errors">
  </div>

  <%= render partial: "bike_events/incident_types", locals: { f: f} %>

  <div class="form-align">
    <div>
      <%= f.label :date %>
      <%= f.datetime_select :occurred_at, start_year:Date.today.year - 7, end_year:Date.today.year, ampm: true%><br>
    </div>

    <div>
      <%= f.label :details%>
      <%= f.text_area :details, cols: 40, rows: 2  %>
    </div>
  </div>

  <div>
    <span id="latitude"> <%= f.hidden_field :latitude  %></span>
    <span id="longitude"> <%= f.hidden_field :longitude  %></span>
  </div>

  <div>
    <%= f.label :avatar, "Attach an Image" %><br>
    <%= f.file_field :avatar, class: "btn btn-xs" %>
  </div><br>

  <div>
    <%= f.submit "Report", class: "btn btn-primary btn-xs" %>
    <%= link_to "Cancel", '#', class: "btn btn-danger btn-xs cancel-button"%>
  </div>

  <% end %>
</div>

app/views/bike_events/_incident_types.html.erb
<h6>Type of Bike Incident (select one:)</h6>

<div class="event-kind">
  <%= f.select(:event_kind) do %>
    <% [['Accident'],
        ['Road Hazard'],
        ['Freak, wildlife incident'],
        ['Other']]
    .each do |c| -%>
      <%= content_tag(:option, c.first, value: c.first) %>
    <% end %>
  <% end %>
</div>

app/views/bike_events/_show.html.erb
<div class="tool-tip row">
  <div class="col-xs-4" id= "event-img">
    <%= image_tag bike_event.avatar_url, width: "100" %>
  </div>
  <div class="col-xs-8 pull-right">
    <%= bike_event.user.username %> reports:
      <div class="event-kind"><%= bike_event.event_kind %> on
        <%= bike_event.date %> @ <%= bike_event.time %><br>
        Details: <%= bike_event.details %>
      </div>

      <% if current_user && current_user.id == bike_event.user_id %>
      <div class="bye">
        <%=link_to "Remove marker", bike_event_path(bike_event.id) %>
      </div>
    <% end %>
  </div>
</div>

app/views/bike_events/index.html.erb
<div> <%= render 'partials/places_search' %></div>
<div id="map-canvas"></div>

<div id="form-incident">
  <%= render partial: "bike_events/form" %>
</div>

<div id="legend"></div>

app/views/bike_events/new.html.erb
<div class="col-xs-6">
    <div class="form">
    HIIIII!!!!
      <h1>Report a Bike Incident</h1>
       <%= render 'form' %>
    </div>  
</div>`

app/views/home/index.html.erb
<div class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">
          <h1>Know the Dangers of the Road</h1>
          <hr class="intro-divider">
          <h3>before you head out for a ride</h3>
        </div>
      </div>
    </div>
  </div>
</div>

<footer>
Accidents and road hazards reported by cyclists for cyclists.
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RideSmart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag "//maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}&libraries=places" %>

  <%= csrf_meta_tags %>
  <% if current_user %>
  <script>
    window.current_user = <%= current_user.attributes.slice("email").to_json.html_safe %>;
  </script>
  <% end %>
</head>


<body class="<%= @body_class %>">
  <%= render 'partials/navbar_v2' %>
  <%= render 'partials/flash_messages' %>

  <%= yield %>

</body>

</html>

app/views/partials/_bike_events_errors.html.erb
<% if @bike_event && @bike_event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
    The form contains <%= pluralize(@bike_event.errors.count, "error") %>.
    </div>
    <ul>
      <% @bike_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_flash_messages.html.erb
<div class="flash">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{name} text-center" %>
  <% end %>
</div>

app/views/partials/_navbar_logged_in_user.html.erb
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hello <%= current_user.username %>!<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to "Logout", logout_path, method: :delete %></li>
    </ul>
</li>
    

app/views/partials/_navbar_v2.html.erb
<nav class='navbar navbar-inverse navbar-fixed-top'>

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand"<%= link_to image_tag("ridesmart-logo-l.png"), root_path %> </a>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Map View <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/bike_events">All Bike Incidents</a></li>

            <li class="divider"></li>
            <li><a href="#" id="accidents">Accidents</a></li>
            <li><a href="#" id="hazards">Road Hazard</a></li>
            <li><a href="#" id="animals">Freak Animal Incidents</a></li>
            <li><a href="#" id="other">Other</a></li>
          </ul>
        </li>
        <!--if current user go to bike events path, else to to login or create account-->
          <% if current_user %>
            <%= render 'partials/navbar_logged_in_user' %>
          <% else %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign Up <span class="caret"></span></a>
          
          <ul class="dropdown-menu" role="menu">
            <li><a href="/auth/google_oauth2">Create account with Google</a></li>
            <li class="divider"></li>
            <li><a href="/users/new">Create account with Email</a></li>
          </ul>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <%= link_to "with Google", "/auth/google_oauth2" %> </li>
            <li class="divider"></li>
            <li> <%= link_to "with Email", login_path %> </li>
          </ul>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_places_search.html.erb
  <input id="pac-input" class="controls" type="text" placeholder="Enter a location">

  <div id="type-selector" class="controls">
    <input type="radio" name="type" id="changetype-all" checked="checked">
    <label for="changetype-all">All</label>

    <input type="radio" name="type" id="changetype-establishment">
    <label for="changetype-establishment">Establishments</label>

    <input type="radio" name="type" id="changetype-address">
    <label for="changetype-address">Addresses</label>

    <input type="radio" name="type" id="changetype-geocode">
    <label for="changetype-geocode">Geocodes</label>
  </div>

app/views/partials/_sample_navbar.html.erb
<nav class='navbar navbar-inverse navbar-fixed-top'>

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" <%= link_to "RideSmart", root_path %></a>
    </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Map View <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">All Bike Incidents</a></li>
            <li class="divider"></li>
            <li><a href="#">Accidents</a></li>
            <li><a href="#">Road Hazards</a></li>
            <li><a href="#">Other</a></li>
          </ul>
        </li>
        <li> <%= link_to "Report an Incident", login_path %> </li>

          <% if current_user %>
            <%= render 'partials/navbar_logged_in_user' %>
          <% else %>
        <li> <%= link_to "Login", login_path %> </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign Up <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">with Google Account</a></li>
            <li class="divider"></li>
            <li><a href="#">with Email</a></li>
          <% end %>
          </ul>
        <li> <%#= link_to "Sign Up", new_user_path %> </li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_user_errors.html.erb
<% if @user && @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="container">
<div class="col-md-6">
  <div class="form-area">  

      <h1 class="extra-cushion">Join Our Riders!</h1>

        <%= form_for(@user, url: users_path, method: :post, role:"form") do |f| %>
          <%= render "partials/user_errors" %>

          <div class="col-md-12">
            <%= f.label :username %>
            <%= f.text_field :username, autofocus: true, class: "form-control"%>
          </div>  

          <div class="col-md-6">
            <%= f.label :password%>
            <%= f.password_field  :password, class: "form-control" %>
          </div>

          <div class="col-md-6">
            <%= f.label :password_confirmation%>
            <%= f.password_field  :password_confirmation, class: "form-control" %>
          </div>

          <div class="col-md-12">
            <%= f.label :email%>
            <%= f.text_field :email, class: "form-control" %>
          </div>

          <div class="col-md-12">
            <%= f.label :twitter_nickname%>
            <%= f.text_field :nickname, class: "form-control" %>
          </div>

          <div class="col-md-12">
            <br><%= f.submit "Create Account", class: "btn btn-primary" %>
          </div>
        <% end %>

        <span class="black-text">Already have an account? <%= link_to "Click here to login", login_path %>
        </span>
      </div>
    </div> 

    <div class="col-xs-5">
      <span class="border-shadow">
         <%= image_tag("bicycle-accident_sm.jpg")%>
      </span> 
    </div>
</div>`